### ISSUE TITLE
Design Log in page

### ISSUE THREAD

**Issue by Sayantan73** [Sayantan73/Hacktoberfest2023#11]
Design a log in page which is user friendly and responsive.

If you open Facebook log in page in desktop mode then you can find how beautifully and easy to use they designed, you can take reference from there don't create same log in page like Facebook log in  use your unique ideas remember it is for a e-commerce website.

If you have any queries then you can ask here and if you willing to create a pull request then leave a comment like this (/attempt #11) and fork the repository and Find log_in.html on this repository to meke your changes use internal css in log_in.html file.

Please note that this is purely for learning purpose not promising any reward or bounty.

**Comment by harshvyas-22** [comment]
I would love to work on this kindly assign it to me /attempt #11

**Comment by Vvvv77777** [comment]
Hi,I am interested in this issue,can you please assign this to me ? @Sayantan73

**Comment by RiaMalvi** [comment]
I want to work on this. Can you assign this to me?

**Comment by harshvyas-22** [comment]
created a pr #13
